export enum NODE_ENV_VALUES {
  DEVELOPMENT = "development",
  PRODUCTION = "production",
  TESTING = "test",
}

export enum PROCESS_ENV_KEYS {
  // # PROJECT
  NODE_ENV = "NODE_ENV",
  // # BACKEND
  BACKEND_SERVICE_HOST = "BACKEND_SERVICE_HOST",
  BACKEND_SERVICE_PORT = "BACKEND_SERVICE_PORT",
  BACKEND_API_VERSION = "BACKEND_API_VERSION",
  BACKEND_API_PREFIX = "BACKEND_API_PREFIX",
  // # CREDENTIALS
  JWT_ACCESS_SECRET_KEY = "JWT_ACCESS_SECRET_KEY",
  JWT_ACCESS_SECRET_EXPIRATION_TIME = "JWT_ACCESS_SECRET_EXPIRATION_TIME",
  JWT_REFRESH_SECRET_KEY = "JWT_REFRESH_SECRET_KEY",
  JWT_REFRESH_SECRET_EXPIRATION_TIME = "JWT_REFRESH_SECRET_EXPIRATION_TIME",
  // # DATABASE
  DATABASE_SERVICE_HOST = "DATABASE_SERVICE_HOST",
  DATABASE_SERVICE_PORT = "DATABASE_SERVICE_PORT",
  DATABASE_PROVIDER = "DATABASE_PROVIDER",
  DATABASE_USERNAME = "DATABASE_USERNAME",
  DATABASE_PASSWORD = "DATABASE_PASSWORD",
  DATABASE_NAME = "DATABASE_NAME",
  DATABASE_URL = "DATABASE_URL",

  // # TESTS
  TEST_USER_USERNAME = "TEST_USER_USERNAME",
  TEST_USER_EMAIL = "TEST_USER_EMAIL",
  TEST_USER_PASSWORD = "TEST_USER_PASSWORD",

  TEST_ADMIN_USERNAME = "TEST_ADMIN_USERNAME",
  TEST_ADMIN_EMAIL = "TEST_ADMIN_EMAIL",
  TEST_ADMIN_PASSWORD = "TEST_ADMIN_PASSWORD",
}
